export type TPermission = (typeof Permissions)[keyof typeof Permissions];

export const Permissions = {
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',

  PERMISSION_TYPE_VIEW: 'PERMISSION_TYPE_VIEW',
  PERMISSION_TYPE_CREATE: 'PERMISSION_TYPE_CREATE',
  PERMISSION_TYPE_UPDATE: 'PERMISSION_TYPE_UPDATE',
  PERMISSION_TYPE_DELETE: 'PERMISSION_TYPE_DELETE',

  COUNTRY_VIEW: 'COUNTRY_VIEW',
  COUNTRY_CREATE: 'COUNTRY_CREATE',
  COUNTRY_UPDATE: 'COUNTRY_UPDATE',
  COUNTRY_DELETE: 'COUNTRY_DELETE',

  DEPOSITORY_COLUMN_VIEW: 'DEPOSITORY_COLUMN_VIEW',
  DEPOSITORY_COLUMN_CREATE: 'DEPOSITORY_COLUMN_CREATE',
  DEPOSITORY_COLUMN_UPDATE: 'DEPOSITORY_COLUMN_UPDATE',
  DEPOSITORY_COLUMN_DELETE: 'DEPOSITORY_COLUMN_DELETE',

  DEPOSITORY_COLUMN_OPTION_VIEW: 'DEPOSITORY_COLUMN_OPTION_VIEW',
  DEPOSITORY_COLUMN_OPTION_CREATE: 'DEPOSITORY_COLUMN_OPTION_CREATE',
  DEPOSITORY_COLUMN_OPTION_UPDATE: 'DEPOSITORY_COLUMN_OPTION_UPDATE',
  DEPOSITORY_COLUMN_OPTION_DELETE: 'DEPOSITORY_COLUMN_OPTION_DELETE',

  DEPOSITORY_COLUMN_VALUE_VIEW: 'DEPOSITORY_COLUMN_VALUE_VIEW',
  DEPOSITORY_COLUMN_VALUE_CREATE: 'DEPOSITORY_COLUMN_VALUE_CREATE',
  DEPOSITORY_COLUMN_VALUE_UPDATE: 'DEPOSITORY_COLUMN_VALUE_UPDATE',
  DEPOSITORY_COLUMN_VALUE_DELETE: 'DEPOSITORY_COLUMN_VALUE_DELETE',

  DEPOSITORY_COLUMN_UPDATE_HISTORY_VIEW: 'DEPOSITORY_COLUMN_UPDATE_HISTORY_VIEW',
  DEPOSITORY_COLUMN_UPDATE_HISTORY_CREATE: 'DEPOSITORY_COLUMN_UPDATE_HISTORY_CREATE',
  DEPOSITORY_COLUMN_UPDATE_HISTORY_UPDATE: 'DEPOSITORY_COLUMN_UPDATE_HISTORY_UPDATE',
  DEPOSITORY_COLUMN_UPDATE_HISTORY_DELETE: 'DEPOSITORY_COLUMN_UPDATE_HISTORY_DELETE',

  APPROVAL_LAYER_VIEW: 'APPROVAL_LAYER_VIEW',
  APPROVAL_LAYER_CREATE: 'APPROVAL_LAYER_CREATE',
  APPROVAL_LAYER_UPDATE: 'APPROVAL_LAYER_UPDATE',
  APPROVAL_LAYER_DELETE: 'APPROVAL_LAYER_DELETE',
  APPROVAL_LAYER_ACTIVATE: 'APPROVAL_LAYER_ACTIVATE',

  APPROVAL_REQUEST_VIEW: 'APPROVAL_REQUEST_VIEW',
  APPROVAL_REQUEST_CREATE: 'APPROVAL_REQUEST_CREATE',
  APPROVAL_REQUEST_UPDATE: 'APPROVAL_REQUEST_UPDATE',
  APPROVAL_REQUEST_DELETE: 'APPROVAL_REQUEST_DELETE',
  APPROVAL_REQUEST_MY_PENDING_REQUEST: 'APPROVAL_REQUEST_MY_PENDING_REQUEST',
  APPROVAL_REQUEST_MY_REQUEST_HISTORIES: 'APPROVAL_REQUEST_MY_REQUEST_HISTORIES',
  APPROVAL_REQUEST_PROCESS: 'APPROVAL_REQUEST_PROCESS',

  VISA_CATEGORY_VIEW: 'VISA_CATEGORY_VIEW',
  VISA_CATEGORY_CREATE: 'VISA_CATEGORY_CREATE',
  VISA_CATEGORY_UPDATE: 'VISA_CATEGORY_UPDATE',
  VISA_CATEGORY_DELETE: 'VISA_CATEGORY_DELETE',

  PENDING_APPROVAL_VIEW: 'PENDING_APPROVAL_VIEW',
  PENDING_APPROVAL_PROCESS: 'PENDING_APPROVAL_PROCESS',

  APPROVAL_HISTORY_VIEW: 'APPROVAL_HISTORY_VIEW',

  MY_REQUESTS_VIEW: 'MY_REQUESTS_VIEW',

  ALL_REQUESTS_VIEW: 'ALL_REQUESTS_VIEW',

  COLUMN_VALUE_UPDATE_HISTORY_VIEW: 'COLUMN_VALUE_UPDATE_HISTORY_VIEW',
  COLUMN_VALUE_UPDATE_HISTORY_CREATE: 'COLUMN_VALUE_UPDATE_HISTORY_CREATE',

  FORBIDDEN: 'FORBIDDEN',
} as const;
