export type TPermission = (typeof Permissions)[keyof typeof Permissions];

export const Permissions = {
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',

  PERMISSION_TYPE_VIEW: 'PERMISSION_TYPE_VIEW',
  PERMISSION_TYPE_CREATE: 'PERMISSION_TYPE_CREATE',
  PERMISSION_TYPE_UPDATE: 'PERMISSION_TYPE_UPDATE',
  PERMISSION_TYPE_DELETE: 'PERMISSION_TYPE_DELETE',

  ARTICLE_VIEW: 'ARTICLE_VIEW',
  ARTICLE_CREATE: 'ARTICLE_CREATE',
  ARTICLE_UPDATE: 'ARTICLE_UPDATE',
  ARTICLE_DELETE: 'ARTICLE_DELETE',

  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  FORBIDDEN: 'FORBIDDEN',
} as const;
